
default: &DEFAULT
  path: &path               /srv/osirim/aaraujo/neuralnet_structured_matrices/models 
  train_dir:                auto
  train_batch_size:         500
  num_epochs:               10
  max_steps:                1000000
  start_new_model:          True
  train_num_gpu:            2
  profiler:                 False

  log_device_placement:     False
  save_checkpoint_steps:    60  # 50K / (num_epoch*gpu)
  save_summaries_steps:     10
  frequency_log_steps:      100

  model:                    MnistModelCirculant
  dense:
    n_layers:               3
    hidden:                 [0, 0, 0]
  circulant:
    n_layers:               placeholder_layers 
    hidden:                 0
    use_diag:               True
    use_bias:               True
  givens:
    n_layers:               3
    hidden:                 [0, 0, 0]
    n_givens:               256
  resnet:
    resnet_size:            18
    bottleneck:             False
    num_filters:            64
    kernel_size:            3
    conv_stride:            1
    first_pool_size:        0
    first_pool_stride:      2
    second_pool_size:       7
    second_pool_stride:     1
    block_sizes:            [2, 2, 2, 2]
    block_strides:          [1, 2, 2, 2]
    final_size:             512
    version:                2
    data_format:            channels_last

  reader:                   MNISTReader
  readers_params:
    num_parallel_calls:     16
    num_parallel_readers:   16 
    prefetch_buffer_size:   50000

  loss:                     SoftmaxCrossEntropyWithLogits
  regularization_penalty:   1.0
  
  lr_strategy:              exponential_decay 
  piecewise_constant:
    boundaries:             [4,8,12,16,20,24]
    values:                 [1.e-1,2.e-2,4.e-3,8.e-4,1.6e-4,3.2e-5,6.4e-6]
  exponential_decay:
    base_lr:                0.05
    lr_decay:               1
    lr_decay_examples:      200000
  cyclic_lr:
    base_lr:                0.01
    min_lr:                 0.001
    max_lr:                 0.1
    step_size_lr:           100
    mode_cyclic_lr:         triangular
    gamma:                  0.99994
  
  optimizer:                MomentumOptimizer
  clip_gradient_norm:       0
  MomentumOptimizer:
    momentum:               0.9 
    use_nesterov:           True
    use_locking:            False
  AdamOptimizer: 
    beta1:                  0.9
    beta2:                  0.999
    epsilon:                1.e-08
    use_locking:            False

train: &TRAIN
  <<: *DEFAULT
  data:
    data_dir:               /home/aaraujo/neuralnet_structured_matrices/data
    data_pattern:           train*

eval: &EVAL
  <<: *DEFAULT
  train_dir:                auto
  data: 
    data_dir:               /home/aaraujo/neuralnet_structured_matrices/data
  eval_batch_size:          512
  eval_num_gpu:             0
  start_eval_from_ckpt:     first
  cherrypick:               None
  start_new_model:          False
  stopped_at_n:             9 

eval_train: &EVAL_TRAIN
  <<: *EVAL
  data:
    data_dir:               /home/aaraujo/neuralnet_structured_matrices/data
    data_pattern:           train*

eval_test: &EVAL_TEST
  <<: *EVAL
  data:
    data_dir:               /home/aaraujo/neuralnet_structured_matrices/data
    data_pattern:           test*

attack: &ATTACK
  <<: *DEFAULT
  <<: *EVAL
  train_dir:                auto
  attack:
    method:                 FGSM
    epsilon:                0.1
    checkpoint:             auto
