
default: &DEFAULT
  train_batch_size:           100
  num_epochs:                 10
  start_new_model:            True
  train_num_gpu:              2
  clear_devices:              False
  profiler:                   False
  compile:                    False
  debug:                      True

  log_device_placement:       False
  save_checkpoint_steps:      500 # ckpt per epoch: dataset_size / (batch_size * gpu)
  save_summaries_steps:       60
  frequency_log_steps:        100

  reader:                     CIFAR10Reader
  one_hot_labels:             False
  per_image_standardization:  False
  dataset_standardization:    False
  grayscale:                  False
  data_augmentation:          False
  readers_params:
    num_parallel_calls:       32
    num_parallel_readers:     16
    prefetch_buffer_size:     2000
    cache_dataset:            False
    drop_remainder:           False

  model:                      Cifar10Model
  cifar_model:
    with_conv:                False
    hidden_layers:            toeplitz
    classification:           dense
    n_layers:                 2
    hidden_size:              0
    use_diag:                 True
    use_bias:                 True
    alpha:                    1.414
    non_linear:               1
    leaky_slope:              0.1
  givens:
    n_layers:                 3
    hidden:                   [0, 0, 0]
    n_givens:                 10
  resnet:
    resnet_size:              18
    bottleneck:               False
    num_filters:              64
    kernel_size:              3
    conv_stride:              1
    first_pool_size:          0
    first_pool_stride:        2
    second_pool_size:         7
    second_pool_stride:       1
    block_sizes:              [2, 2, 2, 2]
    block_strides:            [1, 2, 2, 2]
    final_size:               512
    version:                  2
    data_format:              channels_last
  random_model:
    dp_epsilon:               1.0 
    dp_delta:                 0.05
    attack_norm_bound:        0.1
    noise_after_n_layers:     1
    sensitivity_norm:         l2
    sensitivity_control_scheme: 'bound'
    layer_sensitivity_bounds: ['l2_l2']
  cifar_random_model:
    use_bottleneck:           False
    num_residual_units:       4
    leakyness:                0.1


  loss:                       SoftmaxCrossEntropyWithLogits
  fused_loss:                 True
  reg_norm:                   l2
  weight_decay_rate:          0.0002
  regularization_penalty:     1.0
  
  lr_strategy:                piecewise_constant
  piecewise_constant:
    boundaries:               [40000, 60000, 80000]
    values:                   [0.0005, 0.00025, 0.00005, 0.00001]
  exponential_decay:
    base_lr:                  0.0005
    lr_decay:                 1
    lr_decay_examples:        400000
  cyclic_lr:
    base_lr:                  0.01
    min_lr:                   0.001
    max_lr:                   1
    step_size_lr:             100
    mode_cyclic_lr:           triangular
    gamma:                    0.99994
  
  optimizer:                  AdamOptimizer
  MomentumOptimizer:
    momentum:                 0.9
    use_nesterov:             True
    use_locking:              False
  AdamOptimizer: 
    beta1:                    0.9
    beta2:                    0.999
    epsilon:                  1.e-08
    use_locking:              False
  
  gradients:
    make_gradient_summary:    False
    clip_gradient_norm:       0
    perturbed_gradients:      False
    perturbed_threshold:      0.03
    compute_hessian:          False

  update_ops:
    parseval_update:          True
    parseval_step:            0.0003
    parseval_loops:           10

train: &TRAIN
  <<: *DEFAULT 
  data_pattern:               train*

eval: &EVAL
  <<: *DEFAULT
  eval_under_attack:          False
  eval_batch_size:            200
  eval_num_gpu:               2
  start_eval_from_ckpt:       first
  cherrypick:                 None
  start_new_model:            False
  stopped_at_n:               5 # number of ckpt
  noise_in_eval:              False

eval_test: &EVAL_TEST
  <<: *EVAL
  data_pattern:               test*


attack: &ATTACK
  dump_files:                 False
  eval_under_attack:          True
  eval_batch_size:            200
  eval_num_gpu:               1
  attack_sample:              1


attack_fgm:
  <<: *DEFAULT
  <<: *EVAL_TEST
  <<: *ATTACK
  attack_method:              FastGradientMethod
  FastGradientMethod:
    eps:                      0.3
    ord:                      inf
    clip_min:                 -1.0
    clip_max:                 +1.0

attack_pgd:
  <<: *DEFAULT
  <<: *EVAL_TEST
  <<: *ATTACK
  attack_method:              ProjectedGradientDescent
  ProjectedGradientDescent:
    rand_minmax:              0.3
    eps:                      0.3
    eps_iter:                 0.05
    nb_iter:                  40
    ord:                      inf
    clip_min:                 -1.0
    clip_max:                 +1.0

attack_carlini:
  <<: *DEFAULT
  <<: *EVAL_TEST
  <<: *ATTACK
  eval_batch_size:            20
  attack_method:              CarliniWagnerL2
  CarliniWagnerL2:
    binary_search_steps:      9
    max_iterations:           40
    learning_rate:            1.0e-2
    initial_const:            1.0e-3
    clip_min:                 -1.0
    clip_max:                 +1.0

