
default: &DEFAULT
  # path: &path                 /srv/osirim/aaraujo/neuralnet/grid_search_mom_v2
  path: &path                 /home/aaraujo/neuralnet/models
  data_dir:                   /home/aaraujo/neuralnet/data
  # train_dir:                  auto  
  train_batch_size:           100
  num_epochs:                 100
  start_new_model:            True
  train_num_gpu:              2
  clear_devices:              False
  profiler:                   False
  compile:                    False

  log_device_placement:       False
  save_checkpoint_steps:      600 # ckpt per epoch: 60K / (batch_size * gpu) 
  save_summaries_steps:       60
  frequency_log_steps:        100

  reader:                     CIFAR100Reader
  one_hot_labels:             False
  per_image_standardization:  False
  readers_params:
    num_parallel_calls:       16
    num_parallel_readers:     16
    prefetch_buffer_size:     50000

  model:                      MnistModelDense
  dense:
    n_layers:                 3
    hidden:                   [0, 0, 0]
  circulant:
    n_layers:                 3 # placeholder_n_layers
    hidden:                   0
    use_diag:                 True
    use_bias:                 True
  givens:
    n_layers:                 3
    hidden:                   [0, 0, 0]
    n_givens:                 10
  resnet:
    resnet_size:              18
    bottleneck:               False
    num_filters:              64
    kernel_size:              3
    conv_stride:              1
    first_pool_size:          0
    first_pool_stride:        2
    second_pool_size:         7
    second_pool_stride:       1
    block_sizes:              [2, 2, 2, 2]
    block_strides:            [1, 2, 2, 2]
    final_size:               512
    version:                  2
    data_format:              channels_last
  random_model:
    dp_epsilon:               1.0 
    dp_delta:                 0.05
    attack_norm_bound:        0.1
    noise_after_n_layers:     1
    sensitivity_norm:         l2
    sensitivity_control_scheme: 'bound'
    layer_sensitivity_bounds: ['l2_l2']
  cifar_random_model:
    use_bottleneck:           False
    num_residual_units:       4
    leakyness:                0.1


  loss:                       SoftmaxCrossEntropyWithLogits
  reg_norm:                   l2
  weight_decay_rate:          0.002
  regularization_penalty:     1.0
  
  lr_strategy:                exponential_decay
  piecewise_constant:
    boundaries:               [40000, 60000, 80000]
    values:                   [0.1, 0.01, 0.001, 0.0001]
  exponential_decay:
    base_lr:                  0.01 # placeholder_lr
    lr_decay:                 1
    lr_decay_examples:        400000
  cyclic_lr:
    base_lr:                  0.01
    min_lr:                   0.001
    max_lr:                   1
    step_size_lr:             100
    mode_cyclic_lr:           triangular
    gamma:                    0.99994
  
  optimizer:                  MomentumOptimizer
  MomentumOptimizer:
    momentum:                 0.9
    use_nesterov:             True
    use_locking:              False
  AdamOptimizer: 
    beta1:                    0.9
    beta2:                    0.999
    epsilon:                  1.e-08
    use_locking:              False
  
  gradients:
    clip_gradient_norm:       0
    perturbed_gradients:      False
    perturbed_threshold:      0.01
    compute_hessian:          False

  update_ops:
    parseval_update:          True
    parseval_step:            0.0003
    parseval_loops:           10

train: &TRAIN
  <<: *DEFAULT 
  data_pattern:               train*

eval: &EVAL
  <<: *DEFAULT
  # train_dir:                  auto
  eval_batch_size:            1000
  eval_num_gpu:               0
  start_eval_from_ckpt:       first
  cherrypick:                 None
  start_new_model:            False
  stopped_at_n:               50 # number of ckpt
  noise_in_eval:              True

eval_train: &EVAL_TRAIN
  <<: *TRAIN
  <<: *EVAL

eval_test: &EVAL_TEST
  <<: *EVAL
  data_pattern:               test*

attack: &ATTACK
  <<: *DEFAULT
  <<: *EVAL_TEST
  eval_num_gpu:               2
  path:                       /srv/osirim/aaraujo/neuralnet/mnist_models
  # train_dir:                  auto
  data:
  attack_method:              FastGradientMethod
  adv_processing:             False
  attack:
    CarliniWagnerL2:
      binary_search_steps:    10 
      max_iterations:         100
      learning_rate:          1.0e-2
      initial_const:          1.0e-3
    FastGradientMethod:
      eps:                    0.1
      clip_min:               -1.0
      clip_max:               +1.0


