attack_fgsm: &ATTACK_FGSM
  <<: *DEFAULT
  <<: *EVAL_TEST
  eval_batch_size:            200
  eval_num_gpu:               1
  attack_sample:              1
  attack_method:              FastGradientMethod
  FastGradientMethod:
    eps:                      0.3
    ord:                      inf
    clip_min:                 -1.0
    clip_max:                 +1.0

attack_carlini: &ATTACK_CARLINI
  <<: *DEFAULT
  <<: *EVAL_TEST
  eval_batch_size:            50
  eval_num_gpu:               1
  attack_sample:              1
  attack_method:              CarliniWagnerL2
  CarliniWagnerL2:
    binary_search_steps:      9
    max_iterations:           40
    learning_rate:            1.0e-2
    initial_const:            1.0e-3

attack_pgd: &ATTACK_PGD
  <<: *DEFAULT
  <<: *EVAL_TEST
  eval_batch_size:            200
  eval_num_gpu:               1
  attack_sample:              1
  attack_method:              ProjectedGradientDescent
  ProjectedGradientDescent:
    rand_minmax:              0.3
    eps:                      0.06
    eps_iter:                 0.02
    nb_iter:                  10
    ord:                      inf
    clip_min:                 -1.0
    clip_max:                 +1.0




attack_fgsm_mc_20:
  <<: *ATTACK_FGSM
  eval_batch_size:            10
  attack_sample:              20
attack_carlini_mc_20:
  <<: *ATTACK_CARLINI
  eval_batch_size:            10
  attack_sample:              20
attack_pgd_mc_20:
  <<: *ATTACK_PGD
  eval_batch_size:            10
  attack_sample:              20

attack_fgsm_mc_50:
  <<: *ATTACK_FGSM
  eval_batch_size:            5
  attack_sample:              50
attack_carlini_mc_50:
  <<: *ATTACK_CARLINI
  eval_batch_size:            5
  attack_sample:              50
attack_pgd_mc_50:
  <<: *ATTACK_PGD
  eval_batch_size:            5
  attack_sample:              50

attack_fgsm_mc_100:
  <<: *ATTACK_FGSM
  eval_batch_size:            2
  attack_sample:              100
attack_carlini_mc_100:
  <<: *ATTACK_CARLINI
  eval_batch_size:            2
  attack_sample:              100
attack_pgd_mc_100:
  <<: *ATTACK_PGD
  eval_batch_size:            2
  attack_sample:              100


