
default: &DEFAULT
  path: &path                 /pwrproj/rech/zbe/urz85ee/models
  data_dir:                   /pwrproj/rech/zbe/urz85ee/data
  train_batch_size:           200
  num_epochs:                 200
  start_new_model:            True
  train_num_gpu:              2
  clear_devices:              False
  profiler:                   False
  compile:                    False

  log_device_placement:       False
  save_checkpoint_steps:      250 # ckpt per epoch: dataset_size / (batch_size * gpu)
  save_summaries_steps:       250
  frequency_log_steps:        100

  attack_sample:              1
  train_attack:
    noise_attack:             False
    learn_noise_attack:       False
    attack_method:            ProjectedGradientDescent
    ProjectedGradientDescent:
      rand_minmax:            0.03
      eps:                    0.03
      eps_iter:               0.02
      nb_iter:                1
      ord:                    2
      clip_min:               -1.0
      clip_max:               +1.0
      sanity_checks:          False
  
  reader:                     CIFAR100Reader
  one_hot_labels:             False
  per_image_standardization:  False
  dataset_standardization:    False
  grayscale:                  False
  data_augmentation:          True
  readers_params:
    num_parallel_calls:       32
    num_parallel_readers:     16
    prefetch_buffer_size:     2000
    cache_dataset:            False
    drop_remainder:           False

  model:                      DefenseVsAttack
  dense:
    n_layers:                 1
    hidden:                   0
    use_bias:                 True
    with_conv:                True
  circulant:
    n_layers:                 2
    hidden:                   0
    use_diag:                 True
    use_bias:                 True
    alpha:                    1.414
    with_conv:                False
    non_linear:               1
    leaky_slope:              0.1
  givens:
    n_layers:                 3
    hidden:                   [0, 0, 0]
    n_givens:                 10
  youtube:
    n_layers:                 1      
    hidden:                   0      
    use_bias:                 True   
  low_rank:                          
    n_layers:                 1      
    hidden:                   0      
    use_bias:                 True   
    rank:                     25     
    alpha:                    1.414  
  tensor_train:                      
    n_layers:                 1      
    hidden:                   0      
    rank:                     20     
    use_bias:                 True   
    leaky_slope:              0      
  resnet:
    resnet_size:              18
    bottleneck:               False
    num_filters:              64
    kernel_size:              3
    conv_stride:              1
    first_pool_size:          0
    first_pool_stride:        2
    second_pool_size:         7
    second_pool_stride:       1
    block_sizes:              [2, 2, 2, 2]
    block_strides:            [1, 2, 2, 2]
    final_size:               512
    version:                  2
    data_format:              channels_last
  wide_resnet:
    widen_factor:             10
    depth:                    28
    leaky_slope:              0.1
    dropout:                  0.3
    train_with_noise:         True
    distributions:            l2
    scale_noise:              1
    learn_noise_defense:      False
  random_model:
    dp_epsilon:               1.0 
    dp_delta:                 0.05
    attack_norm_bound:        0.1
    noise_after_n_layers:     1
    sensitivity_norm:         l2
    sensitivity_control_scheme: 'bound'
    layer_sensitivity_bounds: ['l2_l2']
  cifar_random_model:
    use_bottleneck:           False
    num_residual_units:       4
    leakyness:                0.1


  loss:                       SoftmaxCrossEntropyWithLogits
  fused_loss:                 True
  reg_norm:                   l2
  weight_decay_rate:          0.0002
  regularization_penalty:     1.0
  
  lr_strategy:                piecewise_constant
  piecewise_constant:
    boundaries:               [7500, 15000, 20000]
    values:                   [0.1, 0.02, 0.004, 0.00008]
  exponential_decay:
    base_lr:                  0.1
    lr_decay:                 0.97
    lr_decay_examples:        400000
  cyclic_lr:
    base_lr:                  0.01
    min_lr:                   0.001
    max_lr:                   1
    step_size_lr:             100
    mode_cyclic_lr:           triangular
    gamma:                    0.99994
  
  optimizer:                  MomentumOptimizer
  MomentumOptimizer:
    momentum:                 0.9
    use_nesterov:             True
    use_locking:              False
  AdamOptimizer: 
    beta1:                    0.9
    beta2:                    0.999
    epsilon:                  1.e-08
    use_locking:              False
  
  gradients:
    make_gradient_summary:    False
    clip_gradient_norm:       0
    perturbed_gradients:      False
    perturbed_threshold:      0.03
    compute_hessian:          False

  update_ops:
    parseval_update:          False
    parseval_step:            0.0003
    parseval_loops:           10

train: &TRAIN
  <<: *DEFAULT 
  data_pattern:               train*

eval: &EVAL
  <<: *DEFAULT
  eval_batch_size:            400
  eval_num_gpu:               2
  start_eval_from_ckpt:       first
  cherrypick:                 None
  start_new_model:            False
  stopped_at_n:               100 # number of ckpt
  noise_in_eval:              True

eval_train: &EVAL_TRAIN
  <<: *TRAIN
  <<: *EVAL

eval_test: &EVAL_TEST
  <<: *EVAL
  data_pattern:               test*


  
attack_fgsm: &ATTACK_FGSM
  <<: *DEFAULT
  <<: *EVAL_TEST
  eval_batch_size:            200
  eval_num_gpu:               1
  attack_sample:              1
  attack_method:              FastGradientMethod
  FastGradientMethod:
    eps:                      0.3
    ord:                      inf
    clip_min:                 -1.0
    clip_max:                 +1.0

attack_carlini: &ATTACK_CARLINI
  <<: *DEFAULT
  <<: *EVAL_TEST
  eval_batch_size:            50
  eval_num_gpu:               1
  attack_sample:              1
  attack_method:              CarliniWagnerL2
  CarliniWagnerL2:
    binary_search_steps:      9
    max_iterations:           40
    learning_rate:            1.0e-2
    initial_const:            1.0e-3

attack_pgd: &ATTACK_PGD
  <<: *DEFAULT
  <<: *EVAL_TEST
  eval_batch_size:            200
  eval_num_gpu:               1
  attack_sample:              1
  attack_method:              ProjectedGradientDescent
  ProjectedGradientDescent:
    rand_minmax:              0.3
    eps:                      0.06
    eps_iter:                 0.02
    nb_iter:                  10
    ord:                      inf
    clip_min:                 -1.0
    clip_max:                 +1.0




attack_fgsm_mc_20:
  <<: *ATTACK_FGSM
  eval_batch_size:            10
  attack_sample:              20
attack_carlini_mc_20:
  <<: *ATTACK_CARLINI
  eval_batch_size:            10
  attack_sample:              20
attack_pgd_mc_20:
  <<: *ATTACK_PGD
  eval_batch_size:            10
  attack_sample:              20

attack_fgsm_mc_50:
  <<: *ATTACK_FGSM
  eval_batch_size:            5
  attack_sample:              50
attack_carlini_mc_50:
  <<: *ATTACK_CARLINI
  eval_batch_size:            5
  attack_sample:              50
attack_pgd_mc_50:
  <<: *ATTACK_PGD
  eval_batch_size:            5
  attack_sample:              50

attack_fgsm_mc_100:
  <<: *ATTACK_FGSM
  eval_batch_size:            2
  attack_sample:              100
attack_carlini_mc_100:
  <<: *ATTACK_CARLINI
  eval_batch_size:            2
  attack_sample:              100
attack_pgd_mc_100:
  <<: *ATTACK_PGD
  eval_batch_size:            2
  attack_sample:              100


